services:
  pythowncloud:
    build: .
    container_name: pythowncloud-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /home/carlos/pruebas/pythowncloud/data:/data
    environment:
      - POC_API_KEY=${POC_API_KEY}
      - POC_STORAGE_PATH=/data
      - POC_LOGIN_PASSWORD_HASH=${POC_LOGIN_PASSWORD_HASH}
      - POC_SESSION_TTL_DAYS=7
    mem_limit: 128m
    memswap_limit: 192m
